Allow ignoring Pip packages
flatpak/flatpak-builder-tools pull request #217
Opened 2021-08-11 08:14 UTC by strugee

This will allow generating the dep file and then manually fixing it up.

Ref #202

2021-08-11 08:57 UTC, strugee commented
Hrm, looks like for some reason packages I supposedly ignored on the commandline ended up in the final manifest, but using wheel sources? Not sure if that's a feature or a bug...

2023-06-17 17:24 UTC, ENDrain requested changes

2023-06-17 17:24 UTC, ENDrain commented on pip/flatpak-pip-generator
> +                continue
> Hrm, looks like for some reason packages I supposedly ignored on the commandline ended up in the final manifest, but using wheel sources? Not sure if that's a feature or a bug...

It's a feature. This condition is only applied during "Download arch independent packages"  stage. Prior to that wheels are downloaded at line 215/217. You will need to either interfere before that or at the manifest building stage

2023-06-17 18:14 UTC, ENDrain commented on pip/flatpak-pip-generator
> +                    help='Ignore this package, e.g. if the package didn\'t upload source packages to PyPI')
Also, we shouldn't allow for `--ignore-pkg` and `packages` at the same time since that makes no sense. Parameter help should be updated accordingly

2023-08-14 01:54 UTC, bbhtt commented
I've posted an alternative take on this in https://github.com/flatpak/flatpak-builder-tools/pull/364

2023-08-14 05:40 UTC, strugee commented
@bbhtt I'll just close this in favor of your patches then? Realistically I'm not going to get around to fixing up this branch and it seems like you've got a working implementation anyway

2023-08-14 14:46 UTC, closed without merging

2023-08-14 14:46 UTC, strugee commented
Thanks @bbhtt!