Add x-checker-data to flatpak-pip-generator
flatpak/flatpak-builder-tools pull request #248
Opened 2021-12-07 19:27 UTC by JakobDev

For use in [flatpak-external-data-checker](https://github.com/flathub/flatpak-external-data-checker).

Specific versions like foo==1.0 or foo<=1.0 does not work, because I don't know how to use them in x-data-checker.

2021-12-07 20:17 UTC, gasinvein requested changes
We really should pin versions by default, so auto-updating would be opt-in. Maintainer then can enable updating by changing exact version match to something else if they want.
In `x-checker-data` metadata, you can add a `versions` object containing something like `{"==": "1.2.0"}`.

2021-12-07 20:17 UTC, gasinvein commented on pip/flatpak-pip-generator
> +    elif url.endswith(".tar.gz"):
This does include all source file extension, you probably should check all of them, or just use `else:` here.

2021-12-08 20:14 UTC, JakobDev commented
I personally think the x-checker-data should be included by default. The maintainer get only a notice that there are updates available. It's the choice of the maintainer if he/she want to use the updates. Updates can fix bugs and security problems, which is really important.

Another question: I can get the version range of a given package by using packages.but this does not include it's decencies. How can I get the version range of them? I have no idea.

2022-03-14 10:51 UTC, JakobDev commented
Support for x-checker-data was added in #256, so I'm closing this now

2022-03-14 10:51 UTC, closed without merging